### ISSUE TITLE
Cannot use only 1 component back bet

### ISSUE THREAD

**Issue by uksitebuilder** [wabawden/companion-bet-calculator#1]
Hi

Was looking for a multilay spreadsheet, but stumbled across this one for companion betting.

The idea behind it is cool, however when  I try to use it with only one companion bet, it displays an error in the spreadsheet when trying to delete or zero out the 2nd companion bet

**Comment by wabawden** [comment]
Hi Simon.. you've done well to find this! Its only on github because I was planning to turn it into a web app. Are you using excel..? I think the issue is with excel not taking empty cells as zero, whereas Google sheets does (i use Google sheets). The attached copy was edited by someone else to be excel-compatible so should hopefully solve your issue.

Hope you find it useful.. myself and my colleagues have made thousands with this sheet.. its useful for trading price boosts with 0% commission on smarkets.

Have also attached my multilay sheet which is optimised for quick mobile use and will take up to ten selections.

Take care!
Bill
On Friday, 19 March 2021 Simon Powers ***@***.***> wrote:



Hi

Was looking for a multilay spreadsheet, but stumbled across this one for companion betting.

The idea behind it is cool, however when I try to use it with only one companion bet, it displays an error in the spreadsheet when trying to delete or zero out the 2nd companion bet
